name: build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: 'stable'
    - run: nimble -y build -d:release --gc:arc
