name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install libx11-xcb-dev
      run: sudo apt-get install libx11-xcb-dev -y
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
